image: docker:latest

stages:
  - build
  - deploy

build:
  stage: build
  image: node:14.16.1
  script:
    - yarn install --prod
    - yarn build
  artifacts:
    paths:
      - public/
    expire_in: 20 mins

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - build
  script:
    - aws s3 sync ./public s3://$S3_BUCKET_NAME/ --delete
    - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths '/*'
  environment:
    name: production
    url: https://www.davidagood.com
  only:
    - master
