version: 0.1
phases:
    install:
        commands:
            - 'touch .npmignore'
    pre_build:
        commands:
            - 'npm install'
    build:
        commands:
            - 'npm run build'
    post_build:        
        commands:            
            - 'aws s3 rm s3://davidagood.com --recursive'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: yes
